http:
  listener:
    host: "0.0.0.0"
    port: "8081"
    timeout: "300000"
    basepath: "coupaSystemAPI"
    
    reconnection:
      frequency: "2000"
      attempts: "3"
      
  requester:
    exchangeRatePath: "/api/exchange_rates"
    itemPath: "/api/items/"
    lookupValuespath: "/api/lookup_values/"
    expenseReportsPath: "/api/expense_reports/"
    invoicesPath: "/api/invoices/"
    updateInvoicePath : "/api/invoices/{id}"
    invoicesAttachmentPath: "/api/invoices/{invoiceId}/attachments"
    queryParam:
      name: "ACCEPT"
      value: "application/json"

coupa:
  api:
    key: "X-COUPA-API-KEY"
#    value: "![y1KBoTRTLboDQmBDazxt7p4mXBwSWzGD8TYwTjQyxuUlXofoqRwADcypamM49MWp]"
    value: "![pISCmolFCy/DrZ818STTAcRTvajiMhB7zcUbLpoiNGZ7F/TwoB7VytpsUduvKnxf]"
    instance: "zymergen-test.coupahost.com"
    clientId: "![E9Klsl0omkFnIr9olp3ZRZ0SBGDp9jHkDSPaA4eGrkaRsec8anSrrAM/Q9f6dd+3]"
    clientSecret: "![bUFilFXQojt6oJZw8bQp7zxbj9+LtQAkBeg8U1ZPoszTwUqRK7wwUjkM9965mjoK7c3t5cMfsg9zPrKr5KUkFzr7gUQ/6VMq5D7XGPLHx0A=]"
    scopes: "core.accounting.write core.approval.read core.approval.write core.budget.read core.budget.write core.business_entity.read core.business_entity.write core.catalog.read core.catalog.write core.comment.read core.comment.write core.common.read core.common.write core.contract.read core.contract.write core.easy_form_response.approval.write core.easy_form_response.read core.easy_form_response.write core.expense.read core.expense.secure.read core.expense.secure.write core.expense.write core.financial_counterparty.read core.financial_counterparty.write core.global_navigation.read core.integration.read core.integration.write core.inventory.adjustment.read core.inventory.adjustment.write core.inventory.asn.read core.inventory.asn.write core.inventory.balance.read core.inventory.common.read core.inventory.common.write core.inventory.consumption.read core.inventory.consumption.write core.inventory.cycle_counts.read core.inventory.cycle_counts.write core.inventory.pick_list.read core.inventory.pick_list.write core.inventory.receiving.read core.inventory.receiving.write core.inventory.return_to_supplier.read core.inventory.return_to_supplier.write core.inventory.transfer.read core.inventory.transfer.write core.invoice.approval.bypass core.invoice.approval.write core.invoice.create core.invoice.delete core.invoice.read core.invoice.write core.item.read core.item.write core.legal_entity.read core.legal_entity.write core.object_translations.read core.object_translations.write core.order_pad.read core.order_pad.write core.pay.charges.read core.pay.charges.write core.pay.payment_accounts.read core.pay.payments.read core.pay.payments.write core.pay.statements.read core.pay.statements.write core.pay.virtual_cards.read core.pay.virtual_cards.write core.payables.allocations.read core.payables.allocations.write core.payables.expense.read core.payables.expense.write core.payables.external.read core.payables.external.write core.payables.invoice.read core.payables.invoice.write core.payables.order.read core.payables.order.write core.project.read core.project.write core.purchase_order.read core.purchase_order.write core.requisition.read core.requisition.write core.sourcing.pending_supplier.read core.sourcing.pending_supplier.write core.sourcing.read core.sourcing.response.award.write core.sourcing.response.read core.sourcing.response.write core.sourcing.write core.supplier_information_sites.read core.supplier_information_sites.write core.supplier_information_tax_registrations.delete core.supplier_information_tax_registrations.read core.supplier_information_tax_registrations.write core.supplier_sharing_settings.read core.supplier_sharing_settings.write core.supplier_sites.read core.supplier_sites.write core.supplier.read core.supplier.risk_aware.read core.supplier.risk_aware.write core.supplier.write core.uom.read core.uom.write core.user_group.read core.user_group.write core.user.read core.user.write email login offline_access openid profile travel_booking.common.read travel_booking.search.write travel_booking.team.read travel_booking.team.write travel_booking.trip.read travel_booking.trip.write travel_booking.user.read travel_booking.user.write treasury.cash_management.delete treasury.cash_management.read treasury.cash_management.write"
    tokenUrl: "https://zymergen-test.coupahost.com:443/oauth2/token"
    
    reconnection:
      frequency: "2000"
      attempts: "3"
